### ISSUE TITLE
Can not find out Tkinter on Manjaro Linux

### ISSUE THREAD

**Issue by Porrumentzio** [sudo-daemon/libre-DL#1]
Running the file, I get this response:
```
$ python3 libre-DL-unix.py 
Traceback (most recent call last):
  File "/home/porru/Mahaigaina/libre-DL-unix.py", line 1, in <module>
    from tkinter import *
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```
I assume that: or I have Tkinter for Python not installed, or it is not well configured.

Do you know what should I do to run the file?

**Comment by sudo-daemon** [comment]
Yes, it does depend on having tkinter installed.
You can run this command to install it- 

`sudo pacman -S tk`

**Comment by Porrumentzio** [comment]
Thanks! I tried on my main computer (same distro) and works well. I will give news if the problem persists in the other computer

**Comment by bluesnow08** [comment]
Thanks, I have the same issue. But it works.
